server:
  port: 8000
  context-path: /sb-jpa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: 910205
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true

